from .base import BaseRepo
from .users import UsersRepo
from .products import ProductsRepo
from .orders import OrdersRepo
from .favorites import FavoritesRepo
from .feedback import FeedbackRepo
from .notifications import NotificationsRepo
from .chat import ChatRepo
from .logs import LogsRepo
from .reviews import ReviewsRepo
from .categories import CategoriesRepo
from .specifications import SpecificationsRepo