"""Add products and favorites tables and photos

Revision ID: 6aa13d42ab40
Revises: 75c92fec375f
Create Date: 2024-12-07 07:09:14.243320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa13d42ab40'
down_revision: Union[str, None] = '75c92fec375f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('favorites', 'favorite_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favorite_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###
