"""fix_favorites_primary_key

Revision ID: c2a2559e1f0f
Revises: 23e806adf8c0
Create Date: 2025-05-31 00:06:17.005679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a2559e1f0f'
down_revision: Union[str, None] = '23e806adf8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_productpromotions_prod_promo', 'productpromotions', type_='unique')
    op.create_unique_constraint('uq_product_promotion', 'productpromotions', ['product_id', 'promo_id'])
    op.drop_index('uq_product_stat_daily', table_name='productstatistics')
    op.create_unique_constraint('uq_product_stat_daily', 'productstatistics', ['product_id', 'stat_type', 'day'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_stat_daily', 'productstatistics', type_='unique')
    op.create_index('uq_product_stat_daily', 'productstatistics', ['product_id', 'stat_type', sa.text('date(date)')], unique=True)
    op.drop_constraint('uq_product_promotion', 'productpromotions', type_='unique')
    op.create_unique_constraint('uq_productpromotions_prod_promo', 'productpromotions', ['product_id', 'promo_id'])
    # ### end Alembic commands ###
